export const ScreenName = {
    LOGIN_SCREEN: 'LoginScreen',
    LOGIN_EMAIL_SCREEN: 'LoginEmailScreen',
    HOME_SCREEN: 'HomeScreen',
    CART_sCREEN: 'MyCartScreen',
    CATEGORIES_SCREEN: 'CategoriesScreen',
    FAVORITE_SCREEN: 'FAVORITESCREEN',
    MYORDER_SCREEN: 'MyOrderScreen',
    NEWARRIVAL_SCREEN: 'NewArrivalScreen',
    PROFILE_SCREEN: 'ProfileScreen',
    SHIPPINGADDRESS_SCREEN: 'ShippingAddressScreen',
    SETTING_SCREEN: 'SettingScreen',
    BOTTOM_TAB_NAVIGATOR: 'BottomTabNavigator',
    AUTH_STACK: 'AuthNavigation',
    REGISTER_SCREEN: 'RegisterScreen',
    ProductCateFilter_SCREEN: 'ProductCateFilter_SCREEN',
    FillterScreen: 'FillterScreen',
    ProductFilterScreen: 'ProductFilterScreen',
    ProductDetail: 'ProductDetailScreen',
    MyCartAtHome: 'CartAtHome',
    ShippingEdit: 'ShippingEdit',
    Checkout: 'Checkout',
    CheckoutSuccess: 'CheckoutSuccess',
    MyOrderDetail: 'MyOrderDetail',
    BANKINGONLINE:'BankingOnlineScreen'
}